In [1]:
import pandas as pd

url = "C:/Users/suniantara/Desktop/bootcamp/data/Data-Penindakan-Pelanggaran-Lalu-Lintas.csv"
data = pd.read_csv(url)
data

,bulan,wilayah,bap_tilang,stop_operasi,bap_polisi,stop_operasi_polisi,penderekan,ocp_roda_dua,ocp_roda_empat,angkut_motor
0,Januari,Bidang Dalops,44,139,0,0,73,0,0,0
1,Januari,Sudinhub Jakarta Pusat,47,2,52,0,184,237,15,97
2,Januari,Sudinhub Jakarta Utara,166,27,0,0,174,0,0,0
3,Januari,Sudinhub Jakarta Selatan,44,1,0,0,61,42,75,0
4,Januari,Sudinhub Jakarta Barat,184,70,0,0,202,10,5,0
5,Januari,Sudinhub Jakarta Timur,191,141,0,0,137,0,0,0
6,Februari,Bidang Dalops,37,143,0,0,95,2,1,0
7,Februari,Sudinhub Jakarta Pusat,48,7,42,0,175,396,21,143
8,Februari,Sudinhub Jakarta Utara,251,27,31,0,255,3,0,0
9,Februari,Sudinhub Jakarta Selatan,129,12,0,0,155,446,110,0
10,Februari,Sudinhub Jakarta Barat,229,60,0,0,245,12,4,0
11,Februari,Sudinhub Jakarta Timur,276,146,0,0,299,0,0,0
12,Maret,Bidang Dalops,90,203,0,0,150,18,2,0
13,Maret,Sudinhub Jakarta Pusat,68,10,0,0,146,216,1,58
14,Maret,Sudinhub Jakarta Utara,323,37,0,0,285,0,0,0
15,Maret,Sudinhub Jakarta Selatan,479,51,0,0,325,221,87,0
16,Maret,Sudinhub Jakarta Barat,270,101,0,0,318,20,11,0
17,Maret,Sudinhub Jakarta Timur,253,129,0,0,291,22,0,0
18,April,Bidang Dalops,78,108,0,0,139,0,2,0
19,April,Sudinhub Jakarta Pusat,93,21,0,0,166,99,5,117
20,April,Sudinhub Jakarta Utara,293,22,12,0,165,0,0,0
21,April,Sudinhub Jakarta Selatan,454,42,0,0,261,423,64,0
22,April,Sudinhub Jakarta Barat,233,97,0,0,252,0,1,0
23,April,Sudinhub Jakarta Timur,274,113,0,0,264,0,0,0
24,Mei,Bidang Dalops,47,88,0,0,57,0,0,0
25,Mei,Sudinhub Jakarta Pusat,30,10,0,0,46,447,72,244
26,Mei,Sudinhub Jakarta Utara,174,10,16,0,149,0,0,0
27,Mei,Sudinhub Jakarta Selatan,203,29,2,0,169,272,28,0
28,Mei,Sudinhub Jakarta Barat,156,82,0,0,107,0,0,0
29,Mei,Sudinhub Jakarta Timur,162,107,0,0,157,0,0,0
30,Juni,Bidang Dalops,113,129,0,0,119,7,2,0
31,Juni,Sudinhub Jakarta Pusat,24,9,0,0,90,806,8,414
32,Juni,Sudinhub Jakarta Utara,365,29,39,0,206,0,0,0
33,Juni,Sudinhub Jakarta Selatan,390,22,16,0,188,277,51,0
34,Juni,Sudinhub Jakarta Barat,176,81,0,0,157,62,6,0
35,Juni,Sudinhub Jakarta Timur,217,116,0,0,203,0,0,0
36,Juli,Bidang Dalops,72,80,0,0,38,0,0,0
37,Juli,Sudinhub Jakarta Pusat,12,6,0,0,11,146,3,0
38,Juli,Sudinhub Jakarta Utara,224,20,24,0,54,0,0,19
39,Juli,Sudinhub Jakarta Selatan,95,2,8,0,25,160,6,0
40,Juli,Sudinhub Jakarta Barat,36,32,0,0,29,0,0,0
41,Juli,Sudinhub Jakarta Timur,104,72,0,0,110,0,0,0

In [2]:
data['stop_operasi'].mean()

62.69047619047619

In [3]:
data['stop_operasi'].median()

46.5

In [4]:
data['stop_operasi'].mode()

0    10
Name: stop_operasi, dtype: int64

In [5]:
data['stop_operasi'].var()

2750.755516840883

In [6]:
data['stop_operasi'].std()

52.44764548424346

In [10]:
data['stop_operasi'].quantile([0.25,0.25,0.25,0.25])

0.25    20.25
0.25    20.25
0.25    20.25
0.25    20.25
Name: stop_operasi, dtype: float64

In [8]:
data['stop_operasi'].skew()

0.6546836399029299

In [12]:
print(data.dtypes)

bulan                  object
wilayah                object
bap_tilang              int64
stop_operasi            int64
bap_polisi              int64
stop_operasi_polisi     int64
penderekan              int64
ocp_roda_dua            int64
ocp_roda_empat          int64
angkut_motor            int64
dtype: object

In [13]:
data['bulan'] = pd.Categorical(data['bulan'])

In [14]:
print(data.dtypes)

bulan                  category
wilayah                  object
bap_tilang                int64
stop_operasi              int64
bap_polisi                int64
stop_operasi_polisi       int64
penderekan                int64
ocp_roda_dua              int64
ocp_roda_empat            int64
angkut_motor              int64
dtype: object